### ISSUE TITLE
дублювання стилів

### ISSUE THREAD

**Issue by pecourses** [slsq4d/homework#10]
https://github.com/slsq4d/homework/blob/2bced219aa9e2bda1f0d5a4c2bf3f04dc679274f/assets/style.css#L65-L73

- якщо 2 класи мають однакові елементи, то щоб уникнути дублювання, їх зручно записувати разом:
```css
.section-a, .section-b { 
   padding: 10px; 
   color: var(--main-color); 
 } 
``` 

Тут код класів повністю дублюється, можливо є сенс взагалі один клас залишити.
